# EXPOSES MY APPLICATION
apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: react-space
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      # the port is the port on which the service is exposed
      port: {{ .Values.service.port }}
      # the targetPort is the port on which the container listens
      targetPort: {{ .Values.service.containerPort }}
      # the nodePort is the port on which the service is exposed on each node
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}